pass_go/Pass_Go/blueprints/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, ValidationError
from Pass_Go.sql_models import User
from Pass_Go import db_session


class SignUpForm(FlaskForm):
    """Form for creating a new user"""

    username = StringField('User Name',
                           validators=[DataRequired(),
                                       Length(min=3, max=50)])

    email = StringField(
        "Email", validators=[DataRequired(),
                             Length(min=3, max=80),
                             Email()])

    password = PasswordField('Password', validators=[DataRequired()])

    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = db_session.query(User).filter_by(email=self.email.data).first()
        if user:
            raise ValidationError(
                'That email is already in use by a different account.')


class LoginForm(FlaskForm):
    """Form for logging in a user"""
    email = StringField(
        "Email", validators=[DataRequired(),
                             Length(min=3, max=80),
                             Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class ResetPasswordForm(FlaskForm):
    """For resetting a user's password"""
    oldPassword = PasswordField('Old Password', validators=[DataRequired()])
    newPassword = PasswordField('New Password', validators=[DataRequired()])
    submit = SubmitField('Reset Password')

pass_go/Pass_Go/__init__.py
import os, json
from flask import Flask, send_from_directory
from sqlalchemy import create_engine
from Pass_Go.config import Config
import datetime
from sqlalchemy.orm import sessionmaker
from flask_login import LoginManager

config = Config.get_instance()

app = Flask(__name__, static_folder="static")

app.config['SECRET_KEY'] = config.SECRET_KEY
app.config['RTC_SERVICE_URL'] = config.RTC_SERVICE_URL
app.config['SQLALCHEMY_DATABASE_URI'] = config.SQLALCHEMY_DATABASE_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

from Pass_Go.sql_models import (User, Base)

#### SQLALCHEMY SETUP ####
db_engine = create_engine(app.config['SQLALCHEMY_DATABASE_URI'], echo=True)
# create metadata
Base.metadata.create_all(db_engine)
# create session
Session = sessionmaker(bind=db_engine)
db_session = Session()
db_session.commit()

#### AUTH ####
login_manager = LoginManager()
login_manager.init_app(app)


@login_manager.user_loader
def load_user(id):
    return db_session.query(User).get(id)


#### ADD ROUTING ####

from Pass_Go.blueprints.user.routes import User_Blueprint
from Pass_Go.blueprints.main.routes import Main_Blueprint

app.register_blueprint(User_Blueprint, url_prefix='/')
app.register_blueprint(Main_Blueprint, url_prefix='/')


@app.after_request
def after_request(response):
    return response


@app.route("/favicon.ico")
def favicon():
    """Sends the favicon to the client"""
    return send_from_directory(os.path.join(app.root_path, "static"),
                               "./favicon.ico")

pass_go/Pass_Go/blueprints/main/routes.py
from flask import Blueprint, render_template, url_for
import os
import json

Main_Blueprint = Blueprint('main', __name__, template_folder='templates')


@Main_Blueprint.route('/', methods=['GET'])
def home():
    return render_template("home.html")


@Main_Blueprint.route('/go', methods=['GET'])
def go():

    # Get Game Title List
    gameDirectoryList = os.listdir("./Pass_Go/static/games")
    games = []

    for game in gameDirectoryList:
        games.append({
            "title": game,
            "imageUrl": f"games/{game}/title-image.png"
        })

    context = {"games": games}

    return render_template("video_chat.html", **context)


@Main_Blueprint.route('/get_game_url/<gameindex>', methods=['GET'])
def get_game_url(gameindex):

    gameDirectoryList = os.listdir("./Pass_Go/static/games")
    game = gameDirectoryList[int(gameindex)]

    gameFileList = os.listdir(f"./Pass_Go/static/games/{game}")

    htmlFile = ""
    jsFiles = []

    for file in gameFileList:
        if file.endswith('.js'):
            jsFiles.append(url_for("static", filename=f"games/{game}/{file}"))
        elif file.endswith('.html'):
            htmlFile = url_for("static", filename=f"games/{game}/{file}")

    game_url = json.dumps({"js": jsFiles, "html": htmlFile})

    return game_url

pass_go/Pass_Go/blueprints/user/routes.py
from Pass_Go import db_session
from Pass_Go.sql_models import (
    User, )
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from .forms import LoginForm, SignUpForm, ResetPasswordForm

User_Blueprint = Blueprint('user', __name__)


@User_Blueprint.route('/', methods=['GET'])
def home():

    context = {
        'None': None,
    }

    return render_template('home.html', **context)


@User_Blueprint.route('/myprofile', methods=['GET'])
@login_required
def myprofile():
    form = ResetPasswordForm()
    return render_template("profile.html", form=form)


@User_Blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # redirect if alread authed
    if current_user.is_authenticated:
        return redirect(url_for('user.myprofile'))

    # Check if post request and if form is filled
    if request.method == 'POST' and form.validate_on_submit():
        user = db_session.query(User).filter_by(email=form.email.data).first()
        # check hash
        if user and user.check_password(form.password.data):
            # create new session
            login_user(user)
            return redirect(url_for('main.home'))
        else:
            flash("Invalid login details")

    return render_template('login.html', form=form)


@User_Blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    # create signup form
    form = SignUpForm()
    if current_user.is_authenticated:
        return redirect(url_for('user.myprofile'))

    # check if valid creation request and if this email has been used before
    if request.method == 'POST' and form.validate_on_submit() and len(
            db_session.query(User).filter_by(email=form.email.data).all()) < 1:
        new_user = User(email=form.email.data,
                        password=form.password.data,
                        username=form.username.data)
        db_session.add(new_user)
        db_session.commit()
        # create new session
        login_user(new_user)
        return redirect(url_for('user.myprofile'))

    return render_template('signup.html', form=form)


@User_Blueprint.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@User_Blueprint.route('/', methods=['GET', 'POST'])
def create(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass


@User_Blueprint.route('/', methods=['GET'])
def read(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass


@User_Blueprint.route('/', methods=['GET', 'POST'])
def update(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass


@User_Blueprint.route('/', methods=['POST'])
def delete(changename_id):
    pass

pass_go/Pass_Go/blueprints/user/views.py
# from Pass_Go import db_session
# from Pass_Go.sql_models import (
#     # TODO import SQLAlchemy Models
# )
from flask import Blueprint, Flask, request, redirect, render_template, url_for

User_Blueprint = Blueprint('user', __name__)


@User_Blueprint.route('/', methods=['GET'])
def home():

    context = {
        'None': None,
    }
    
    return render_template('home.html', **context)

@User_Blueprint.route('/', methods=['GET', 'POST'])
def create(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass

@User_Blueprint.route('/', methods=['GET'])
def read(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass

@User_Blueprint.route('/', methods=['GET', 'POST'])
def update(changename_id):
    if request.method == 'POST':
        pass
    else:
        pass
    pass

@User_Blueprint.route('/', methods=['POST'])
def delete(changename_id):
    pass

pass_go/Pass_Go/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pass And Go</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

    <!-- Custom Styles -->
    <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="/static/images/pass-and-go-logo.png" alt="" width="30" height="30"
                    class="d-inline-block align-top">
                Pass And Go
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/go">Play</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    <li>
                        <a class="nav-link profile-icon" href="/myprofile">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="white">
                                <path
                                    d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 22c-3.123 0-5.914-1.441-7.749-3.69.259-.588.783-.995 1.867-1.246 2.244-.518 4.459-.981 3.393-2.945-3.155-5.82-.899-9.119 2.489-9.119 3.322 0 5.634 3.177 2.489 9.119-1.035 1.952 1.1 2.416 3.393 2.945 1.082.25 1.61.655 1.871 1.241-1.836 2.253-4.628 3.695-7.753 3.695z" />
                            </svg>
                        </a>
                    </li>
                    </form>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="text-center p-3 bg-dark text-light">

        <p class="fs-5 m-0">Copyright Pass And Go 2021.</p>

    </footer>

    {% block scripts %}{% endblock %}

</body>



</html>

pass_go/Pass_Go/templates/comp_fly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bird Game</title>
    <link href="{{ url_for('static', filename='comp_fly/style.css') }}" rel="stylesheet"
    type="text/css" />
</head>
<body>
    <div id="game-window">

    <!-- This is the box the game sits in-->
    <canvas id="canvas1"></canvas>

    <script src="{{ url_for('static', filename='comp_fly/script.js') }}"></script>
    </div>
</body>
</html>

pass_go/Pass_Go/templates/dtd_game.html
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

<style>
    body {
        margin: 0;
        background: black;
    }
</style>

<div class="fixed text-white text-sm ml-2 mt-1 select-none">
    <span>Score: </span><span id="scored">0</span>
</div>

<div class="fixed inset-0 flex items-center justify-center" id="modalEl">
    <div class="bg-white max-w-md w-full p-6 text-center rounded-md">
        <h1 class="text-4xl font-bold select-none leading-none">0</h1>
        <p class="text-sm text-gray-500 mb-3 select-none">Points</p>
        <div>
            <button class="bg-blue-600 text-sm text-white w-full py-3 rounded-full select-none" id="startGameBtn">Start Game</button>
        </div>
        <button></button>
    </div>
</div>

<canvas></canvas>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js" integrity="sha512-1dalHDkG9EtcOmCnoCjiwQ/HEB5SDNqw8d4G2MKoNwjiwMNeBAkudsBCmSlMnXdsH8Bm0mOd3tl/6nL5y0bMaQ==" crossorigin="anonymous"></script>
<script src="../games/dtd_game.js"></script>

pass_go/Pass_Go/templates/login.html
{% extends 'base.html' %}
{% block content %}

<section class="auth-section">

    <div class="auth-container">
        <p class="fs-3 text-center">Login</p>
        <form action="{{ url_for('user.login', next=request.args.get('next')) }}" method="POST">
            {{ form.csrf_token }}
            <fieldset>

                <div class="input-wrapper">
                    {{ form.email.label(class_="form-label") }}
                    {{ form.email(class_="form-control") }}
                </div>
                <ul>
                    {% for error in form.email.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>

                <div class="input-wrapper">
                    {{ form.password.label(class_="form-label") }}
                    {{ form.password(class_="form-control") }}
                </div>
                <ul>
                    {% for error in form.password.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>

                <div class="input-wrapper">
                    {{ form.submit(class_="btn btn-primary") }}
                </div>

                {% for message in get_flashed_messages() %}
                <div>
                    <p class="error">{{ message }}</p>
                </div>
                {% endfor %}

            </fieldset>
        </form>
    </div>
    <p>Don't Have an Account? <a href="{{url_for('user.signup')}}">Signup</a></p>

</section>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

pass_go/Pass_Go/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<section class="profile-stat-section">
    <div class="profile-header">
        <a class="nav-link profile-icon" href="/myprofile">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24">
                <path
                    d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 22c-3.123 0-5.914-1.441-7.749-3.69.259-.588.783-.995 1.867-1.246 2.244-.518 4.459-.981 3.393-2.945-3.155-5.82-.899-9.119 2.489-9.119 3.322 0 5.634 3.177 2.489 9.119-1.035 1.952 1.1 2.416 3.393 2.945 1.082.25 1.61.655 1.871 1.241-1.836 2.253-4.628 3.695-7.753 3.695z" />
            </svg>
        </a>

        <p class="profile-name">{{current_user.username}}</p>
    </div>
    <div class="user-stats-container">
        <div class="flex-row">
            <div class="user-stat">
                <p class="fs-4 text-med">Stats:</p>
                <p><strong>Total Games:</strong> 11</p>
                <p><strong>Wins:</strong> 4</p>
                <p><strong>Losses:</strong> 7</p>
            </div>
            <div class="user-stat">
                <p class="fs-4 text-med">Kills:</p>
                <p><strong>Total Kills:</strong> 2</p>
                <p><strong>Total Deaths:</strong> 10</p>
                <p><strong>KDR:</strong> 0.2</p>
            </div>
        </div>
        <div class="flex-row">
            <div class="user-stat">
                <p class="fs-4 text-med">User Impact:</p>
                <p><strong>Total Games:</strong> 11</p>
                <p><strong>Unique Users Met:</strong> 11</p>
            </div>
            <div class="user-stat">
                <p class="fs-4 text-med">Reputation Score:</p>
                <p><strong>Total Rep Earned:</strong> 40</p>
                <p><strong>Rep Score:</strong> 90/100</p>
            </div>
        </div>
    </div>

</section>
<section class="profile-setting-section">
    <p class="fs-3 mb-0 mx-4 text-center">User Settings</p>
    <div class="col-10 offset-1">
        <div class="user-settings-container col-6 offset-3 mb-5">

            <p class="fs-5"><strong>Reset Password:</strong></p>

            <form action="" method="POST">
                {{ form.csrf_token }}
                <fieldset>
                    <div class="input-wrapper">
                        {{ form.oldPassword.label(class_="form-label") }}
                        {{ form.oldPassword(class_="form-control") }}
                    </div>
                    <ul>
                        {% for error in form.oldPassword.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>

                    <div class="input-wrapper">
                        {{ form.newPassword.label(class_="form-label") }}
                        {{ form.newPassword(class_="form-control") }}
                    </div>
                    <ul>
                        {% for error in form.newPassword.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>

                    {{ form.submit(class_="btn btn-primary") }}
                </fieldset>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

pass_go/Pass_Go/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<section class="auth-section">

    <div class="auth-container">
        <p class="fs-3 text-center">Create an Account</p>
        <form action="{{url_for('user.signup')}}" method="POST">
            {{ form.csrf_token }}
            <fieldset>

                <div class="input-wrapper">
                    {{ form.username.label(class_="form-label") }}
                    {{ form.username(class_="form-control") }}
                </div>
                <ul>
                    {% for error in form.username.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>

                <div class="input-wrapper">
                    {{ form.email.label(class_="form-label") }}
                    {{ form.email(class_="form-control") }}
                </div>
                <ul>
                    {% for error in form.email.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>

                <div class="input-wrapper">
                    {{ form.password.label(class_="form-label") }}
                    {{ form.password(class_="form-control") }}
                </div>
                <ul>
                    {% for error in form.password.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>

                <div class="input-wrapper">
                    {{ form.submit(class_="btn btn-primary") }}
                </div>
            </fieldset>
        </form>
    </div>

</section>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

pass_go/Pass_Go/templates/video_chat.html
{% extends 'base.html' %}
{% block content %}


<section class="video-section">

    <div class="window-container-row">
        <div class="game-window-wrapper">
            <div class="content-window" id="game-window">
                <div class="window-title row m-0 p-0">
                    <div class="col-6 offset-3 text-center">
                        <p class="noselect">Game Window</p>
                    </div>
                    <div class="popout-button col-3 text-right">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                            style="fill: #fff">
                            <path d="M0 3v18h24v-18h-24zm22 16h-4v-10h-16v-4h20v14z" />
                        </svg>
                    </div>
                    <!--Games Library -->
                    <div class="container m-1 text-center">
                        <div class="row align-items-start">
                            <div class="game-container" id="game-container">
                                {% for game in games %}
                                <div class="card border-light m-3 gameTile">
                                    <div class="card-header text-secondary">{{game.title}}
                                    </div>
                                    <div class="card-body">
                                        <div class="game-image-wrapper">
                                            <img src="{{ url_for('static', filename=game.imageUrl) }}"
                                                class="gameImage" />
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div id="canvas-container">
                    <!-- canvas is dynamically inserted here -->
                </div>
            </div>
        </div>
        <div class="window-container-column">
            <div class="video-window-wrapper">
                <div class="content-window" id="opponent-video-window">
                    <div class="window-title row m-0 p-0">
                        <div class="col-6 offset-3 text-center">
                            <p class="noselect">Other Player Video</p>
                        </div>
                        <div class="popout-button col-3 text-right">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                style="fill: #fff">
                                <path d="M0 3v18h24v-18h-24zm22 16h-4v-10h-16v-4h20v14z" />
                            </svg>
                        </div>
                    </div>
                    <div class="streamControls">
                        <div class="muteButtonWrapper">
                            <div id="findMatch" class="findMatchButton">
                                <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd"
                                    clip-rule="evenodd">
                                    <path
                                        d="M13.818 16.646c-1.273.797-2.726 1.256-4.202 1.354l-.537-1.983c2.083-.019 4.132-.951 5.49-2.724 2.135-2.79 1.824-6.69-.575-9.138l-1.772 2.314-1.77-6.469h6.645l-1.877 2.553c3.075 2.941 3.681 7.659 1.423 11.262l7.357 7.357-2.828 2.828-7.354-7.354zm-11.024-1.124c-1.831-1.745-2.788-4.126-2.794-6.522-.005-1.908.592-3.822 1.84-5.452 1.637-2.138 4.051-3.366 6.549-3.529l.544 1.981c-2.087.015-4.142.989-5.502 2.766-2.139 2.795-1.822 6.705.589 9.154l1.774-2.317 1.778 6.397h-6.639l1.861-2.478z" />
                                </svg>
                            </div>
                        </div>
                    </div>
                    <video id="remoteStream" class="video-stream" autoplay playsinline></video>
                </div>
            </div>

            <div class="video-window-wrapper">
                <div class="content-window" id="user-video-window">
                    <div class="window-title row m-0 p-0">
                        <div class="col-6 offset-3 text-center">
                            <p class="noselect">User Video</p>
                        </div>
                        <div class="popout-button col-3 text-right">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                style="fill: #fff">
                                <path d="M0 3v18h24v-18h-24zm22 16h-4v-10h-16v-4h20v14z" />
                            </svg>
                        </div>
                    </div>
                    <div class="streamControls">
                        <div class="muteButtonWrapper">
                            <div id="cameraMute" class="muteButton buttonOn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path
                                        d="M16 16c0 1.104-.896 2-2 2h-12c-1.104 0-2-.896-2-2v-8c0-1.104.896-2 2-2h12c1.104 0 2 .896 2 2v8zm8-10l-6 4.223v3.554l6 4.223v-12z" />
                                </svg>
                            </div>
                        </div>
                        <div class="muteButtonWrapper">
                            <div id="micMute" class="muteButton buttonOn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path
                                        d="M16 11c0 2.209-1.791 4-4 4s-4-1.791-4-4v-7c0-2.209 1.791-4 4-4s4 1.791 4 4v7zm4-2v2c0 4.418-3.582 8-8 8s-8-3.582-8-8v-2h2v2c0 3.309 2.691 6 6 6s6-2.691 6-6v-2h2zm-7 13v-2h-2v2h-4v2h10v-2h-4z" />
                                </svg>
                            </div>
                        </div>
                    </div>
                    <video id="localStream" class="video-stream" autoplay playsinline muted></video>

                </div>
            </div>
        </div>
    </div>

    <div id="ghostpane"></div>
</section>



{% endblock content %}

{% block scripts %}

<!-- Socket IO -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.1/socket.io.min.js"></script>

<!-- Drag and drop functionality -->
<script src="{{ url_for('static', filename='js/window-management.js') }}"></script>

<!-- Video Chat Manager -->
<script src="{{ url_for('static', filename='js/video-chat.js') }}"></script>

<!-- Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Game Manager -->
<script src="{{ url_for('static', filename='js/game-manager.js') }}"></script>

{% endblock scripts %}